### PR TITLE
added KL divergence computation

### PR DESCRIPTION
**Pull request by lluciesmith**
Hi Davide, 

I have included the ability to return the KL-divergence instead of mutual information if requested. I have added a test to ensure the KL estimate is within 2sigma of the analytic solution for a simple Gaussian case.

Another important change I would like to suggest is that if one calls the ``fit'' method (which actually doesn't _just_ do the fit, but also returns the MI estimates) for an estimator that was already previously fitted, the code does not re-do the GMM fit a second time but directly skips to the MI (or KL) estimation.

Please let me know if you agree with this.

Best wishes,
Luisa

### CODE REVIEW

**Comment by dpiras** [comment]
Hi Luisa! I am having a look and this is definitely relevant.

Since we are moving towards the direction of fitting the model, and _then_ obtaining more than one quantity of interest (MI, KL), I think it might be worth restyling the whole code so that there is a fitting part, and then a separate set of functions which compute the quantities of interest upon calling them. I'm thinking on the lines of standard `sklearn` approach, like the [Examples here](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html).

I'm happy to take it from what you have done so far and make it such that GMM-MI works as something like:
```
gmm_fit = gmm_mi.Estimator.fit(X)
MI_mean, MI_std = gmm_fit.MI()
KL_mean, KL_std = gmm_fit.KL()
```
This is a major change in the overall structure (and we would need to change the README and all notebooks), but I think it would make GMM-MI more flexible and clearer to use. As I said, I'm happy to use this PR as a starting point for that. What do you think?

**Comment by dpiras** [comment]
(of course, in this situation, once the fit is done with `gmm_fit = gmm_mi.Estimator.fit(X)` there wouldn't be any need to re-do the fit every time for MI and KL. Also, this would be only for the continuous case, as I think there is no interesting KL to estimate in the categorical case)

**Comment by lluciesmith** [comment]
@dpiras yes I think that would look a lot better! i.e. what you suggested here:

```
gmm_fit = gmm_mi.Estimator.fit(X)
MI_mean, MI_std = gmm_fit.MI()
KL_mean, KL_std = gmm_fit.KL()
```

Do we also still want to have a higher-level function that does the fit and and the MI computation in one go? Just in case some users also want the ability to quickly get MI without having to write up the "fit()" and then "MI()" step separately. The MI estimate is still the primary output of the code -- the KL is just a quick add that comes basically for free

**Comment by dpiras** [comment]
I think that should be doable (just like in `sklearn` there is the `fit` function, and the `fit_predict` function). Happy to start working on this from this PR if you agree!

**Comment by dpiras** [comment]
Or actually, I can merge this one and then open a new one for the major change we are discussing.

**Comment by lluciesmith** [comment]
Yep I'm happy for you to merge this one and open a new one. Thanks for putting work into this change!

**Pull request merged**
